name: Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          run: |
           docker buildx build --file Dockerfile --tag surendra183/my-flask-app:latest .
            echo "$dckr_pat_xHGRVQEmrXZOqutdyiQ8wopuG8s" | docker login --username "$surendra183" --password-stdin
           docker push surendra183/my-flask-app:latest
